{{- range $i, $e := until 3 }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ $.Values.clusterName }}-{{ $i }}
  labels:
    application: {{ $.Values.application }}
    cluster-name: {{ $.Values.clusterName }}
    citus-group: "{{ $i }}"
    citus-type: {{ if eq $i 0 }}coordinator{{ else }}worker{{ end }}
subsets: []
---
{{- end }}