# headless services to avoid deletion of citusdemo-*-config endpoints
{{- range $i, $e := until 3 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.clusterName }}-{{ $i }}-config
  labels:
    application: {{ $.Values.application }}
    cluster-name: {{ $.Values.clusterName }}
    citus-group: "{{ $i }}"
spec:
  clusterIP: None
---
{{- end }}

{{- range $i, $e := until 3 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.clusterName }}-{{ $i }}
  labels:
    application: {{ $.Values.application }}
    cluster-name: {{ $.Values.clusterName }}
    citus-group: "{{ $i }}"
    citus-type: {{ if eq $i 0 }}coordinator{{ else }}worker{{ end }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
---
{{- end }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.clusterName }}-workers
  labels:
    application: {{ $.Values.application }}
    cluster-name: {{ $.Values.clusterName }}
    citus-type: worker
    role: master
spec:
  type: ClusterIP
  selector:
    application: {{ $.Values.application }}
    cluster-name: {{ $.Values.clusterName }}
    citus-type: worker
    role: master
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.clusterName }}-external
  labels:
    application: {{ $.Values.application }}
    cluster-name: {{ $.Values.clusterName }}
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432